/*
 * The MIT License
 *
 * Copyright 2013 Venkat Ram Akkineni.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.netbeans.modules.plantumlnb.ui;

import java.awt.BorderLayout;
import java.io.Serializable;
import javax.swing.ActionMap;
import javax.swing.JScrollPane;
import javax.swing.JToolBar;
import org.netbeans.api.settings.ConvertAsProperties;
import org.netbeans.modules.plantumlnb.SVGImagePreviewPanel;
import org.netbeans.modules.plantumlnb.pumlDataObject;
import org.netbeans.modules.plantumlnb.ui.io.PUMLGenerator;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.filesystems.FileObject;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.util.NbBundle.Messages;
import org.openide.util.Utilities;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.util.lookup.Lookups;
import org.openide.util.lookup.ProxyLookup;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.netbeans.modules.plantumlnb//PUML//EN",
    autostore = false
)
@TopComponent.Description(
    preferredID = "PUMLTopComponent",
    iconBase = "org/netbeans/modules/plantumlnb/icon.png",
    persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(
    mode = "properties",
    openAtStartup = false
)
@ActionID(
    category = "Window",
    id = "org.netbeans.modules.plantumlnb.PUMLTopComponent"
)
@ActionReference(
    path = "Menu/Window",
    position = 19042
)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_PUMLAction",
    preferredID = "PUMLTopComponent"
)
@Messages({
    "CTL_PUMLAction=PlantUML",
    "CTL_PUMLTopComponent=PlantUML",
    "HINT_PUMLTopComponent=This is a PlantUML window"
})
public final class PUMLTopComponent extends TopComponent implements Serializable {

    private static final long serialVersionUID = -99094945997905090L;

    private final InstanceContent instanceContent = new InstanceContent();

    /**
     * current context to work on
     */
    private final Lookup.Result currentContext;

    /**
     * listener to context changes
     */
    private final LookupListener contextListener;

    private pumlDataObject currentDataObject;

    /**
      * holds UI of this panel
      */
    private SVGImagePreviewPanel panelUI;
    private JScrollPane scrollPane;
    private JToolBar jToolBar1 = null;

    private PUMLTopComponent() {
        initComponents();
        addCustomComponents();
        setName(Bundle.CTL_PUMLTopComponent());
        setToolTipText(Bundle.HINT_PUMLTopComponent());

        //connect standard CTRL-C action (in menu/toolbar) to own action
        ActionMap actionMap = getActionMap();
        actionMap.put("copy-to-clipboard",
                org.openide.awt.Actions.forID("PlantUML", "org.netbeans.modules.plantumlnb.ui.actions.CopyToClipboard"));
        associateLookup(new ProxyLookup(
                Lookups.fixed(actionMap),
                new AbstractLookup(instanceContent)));

        WindowManager.getDefault().findMode("properties").dockInto(this);

        contextListener = (LookupEvent le) -> updateDataObject();

        currentContext = Utilities.actionsGlobalContext().lookupResult(pumlDataObject.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomComponents() {
        panelUI = new SVGImagePreviewPanel();
        scrollPane = new javax.swing.JScrollPane();
        jToolBar1 = new Toolbar(panelUI);
        scrollPane.setViewportView(panelUI);

        add(scrollPane, BorderLayout.CENTER);
        add(jToolBar1, BorderLayout.SOUTH);
    }// </editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void updateDataObject() {
        pumlDataObject pumlDataObject = Utilities.actionsGlobalContext().lookup(pumlDataObject.class);
        if (pumlDataObject != null) {
            if (currentDataObject != pumlDataObject) {
                pumlDataObject oldDataObject = currentDataObject;
                currentDataObject = pumlDataObject;
                if (oldDataObject != null) {
                    instanceContent.remove(oldDataObject);
                }
                instanceContent.add(currentDataObject);
                panelUI.renderSVGFile(() -> {
                    FileObject fo = pumlDataObject.getPrimaryFile();
                    return PUMLGenerator.getInstance().generateSvgString(fo);
                });
            }
        }
    }


    @Override
    protected void componentClosed() {
        super.componentClosed();
        currentContext.removeLookupListener(contextListener);
    }

    @Override
    protected void componentOpened() {
        super.componentOpened();
        currentContext.addLookupListener(contextListener);
        updateDataObject();
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

}
